import {
  Shop,
  User,
  Product,
  Customer,
  Supplier,
  Order,
  IncompleteOrder,
  Purchase,
  StockMovement,
  PaymentTransaction,
  LandingPage,
  CourierOrder,
  BlockedEntity,
  NotificationSettings,
  FacebookPixelSettings,
} from '../types';

export const initialShop: Shop = {
  id: 'shop_101',
  name: 'স্মার্ট ফ্যাশন অ্যান্ড গ্যাজেট',
  ownerName: 'তানভীর আহমেদ',
  mobile: '01711002233',
  email: 'tanvir@smartshopx.com',
  address: 'দোকান নং ৪২, লেভেল ৩, বসুন্ধরা সিটি, পান্থপথ, ঢাকা',
  category: 'Mobile & Telecom',
  customCategory: 'Mobile Accessories',
  logo: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=150&auto=format&fit=crop&q=60',
  banner: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&auto=format&fit=crop&q=60',
  currency: 'BDT',
  subscriptionPlan: 'Standard',
  subscriptionStatus: 'Active',
  subscriptionStart: '2026-01-01',
  subscriptionExpiry: '2026-12-31',
  storeSlug: 'smartfashion-dhaka',
  storePublished: true,
  deliveryChargeInside: 70,
  deliveryChargeOutside: 130,
};

export const initialUser: User = {
  id: 'usr_001',
  name: 'তানভীর আহমেদ',
  mobile: '01711002233',
  email: 'tanvir@smartshopx.com',
  role: 'owner',
  shopId: 'shop_101',
  permissions: {
    canViewSales: true,
    canCreateSale: true,
    canManageProducts: true,
    canManageCustomers: true,
    canManageOrders: true,
    canViewReports: true,
    canManagePayments: true,
  },
};

export const initialProducts: Product[] = [
  {
    id: 'prod_1',
    name: 'Wireless Bluetooth Earbuds Pro (ANC)',
    sku: 'EAR-ANC-01',
    barcode: '890123456001',
    category: 'Mobile & Telecom',
    brand: 'Anker Soundcore',
    purchasePrice: 1800,
    sellingPrice: 2650,
    discount: 150,
    stock: 24,
    minStock: 5,
    unit: 'পিস (Pcs)',
    description: 'উচ্চমানের নয়েজ ক্যান্সেলেশন এবং ৩০ ঘণ্টা ব্যাটারি ব্যাকআপ সমৃদ্ধ ওয়্যারলেস এয়ারবাডস।',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-02-01',
  },
  {
    id: 'prod_2',
    name: '20W PD Fast Charger Adapter (Type-C)',
    sku: 'CHG-20W-PD',
    barcode: '890123456002',
    category: 'Mobile & Telecom',
    brand: 'Baseus',
    purchasePrice: 450,
    sellingPrice: 750,
    discount: 50,
    stock: 45,
    minStock: 10,
    unit: 'পিস (Pcs)',
    description: 'আইফোন ও অ্যান্ড্রয়েড সাপোর্টেড আল্ট্রা-ফাস্ট চার্জিং অ্যাডাপ্টার।',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-02-05',
  },
  {
    id: 'prod_3',
    name: '10,000mAh Magnetic Power Bank with Stand',
    sku: 'PB-10K-MAG',
    barcode: '890123456003',
    category: 'Mobile & Telecom',
    brand: 'Remax',
    purchasePrice: 1200,
    sellingPrice: 1850,
    discount: 100,
    stock: 4, // low stock!
    minStock: 8,
    unit: 'পিস (Pcs)',
    description: 'ম্যাগনেটিক ওয়্যারলেস ও ক্যাবল চার্জিং সুবিধা সহ স্লিম পাওয়ার ব্যাংক।',
    image: 'https://images.unsplash.com/photo-1609592424369-15832a829e0a?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-02-10',
  },
  {
    id: 'prod_4',
    name: 'Smart Watch Series 9 AMOLED Display',
    sku: 'SW-S9-AMOLED',
    barcode: '890123456004',
    category: 'Electronics',
    brand: 'Havit',
    purchasePrice: 2100,
    sellingPrice: 3200,
    discount: 200,
    stock: 12,
    minStock: 5,
    unit: 'পিস (Pcs)',
    description: 'ব্লুটুথ কলিং, হার্টরেট মনিটর ও ওয়াটারপ্রুফ প্রিমিয়াম স্মার্টওয়াচ।',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-02-15',
  },
  {
    id: 'prod_5',
    name: 'Heavy Duty Shockproof Armor Case (iPhone 15)',
    sku: 'CASE-IP15-ARM',
    barcode: '890123456005',
    category: 'Mobile & Telecom',
    brand: 'Spigen Look',
    purchasePrice: 280,
    sellingPrice: 550,
    discount: 0,
    stock: 2, // low stock!
    minStock: 10,
    unit: 'পিস (Pcs)',
    description: 'মিলিটারি গ্রেড ড্রপ প্রোটেকশন ব্যাক কভার।',
    image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-02-18',
  },
  {
    id: 'prod_6',
    name: 'Premium Casual Cotton Polo Shirt',
    sku: 'POLO-COT-NVY',
    barcode: '890123456006',
    category: 'Clothing',
    brand: 'SmartShop Exclusive',
    purchasePrice: 420,
    sellingPrice: 850,
    discount: 50,
    stock: 0, // out of stock
    minStock: 10,
    unit: 'পিস (Pcs)',
    description: '১০০% কম্বড কটন প্রিমিয়াম ওয়াশ পোলো শার্ট।',
    image: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: false,
    createdAt: '2026-02-20',
  },
  {
    id: 'prod_7',
    name: 'RGB Mechanical Gaming Keyboard (Blue Switch)',
    sku: 'KB-MECH-RGB',
    barcode: '890123456007',
    category: 'Electronics',
    brand: 'Redragon',
    purchasePrice: 1900,
    sellingPrice: 2800,
    discount: 100,
    stock: 15,
    minStock: 5,
    unit: 'পিস (Pcs)',
    description: 'কাস্টমাইজেবল ব্যাকলাইট ও মেকানিক্যাল ব্লু সুইচ কিবোর্ড।',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-02-22',
  },
  {
    id: 'prod_8',
    name: '60W Braided Type-C to Type-C Cable (1.5m)',
    sku: 'CAB-CC-60W',
    barcode: '890123456008',
    category: 'Mobile & Telecom',
    brand: 'Baseus',
    purchasePrice: 160,
    sellingPrice: 320,
    discount: 20,
    stock: 35,
    minStock: 10,
    unit: 'পিস (Pcs)',
    description: 'টেকসই নাইলন ব্রেইডেড ফাস্ট চার্জিং ও ডেটা কেবল।',
    image: 'https://images.unsplash.com/photo-1608755728617-aefab37d2edd?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-02-25',
  },
  {
    id: 'med_1',
    name: 'Napa Extra Tablet',
    sku: 'MED-NAP-EXT',
    barcode: '890123456101',
    category: 'Pharmacy & Medicine',
    subCategory: 'জ্বর ও ব্যথানাশক (Fever & Pain)',
    brand: 'Beximco Pharma',
    manufacturer: 'Beximco Pharmaceuticals Ltd.',
    genericName: 'Paracetamol + Caffeine (500mg + 65mg)',
    dosageForm: 'Tablet',
    strength: '500mg + 65mg',
    batchNumber: 'BEX-8829',
    expiryDate: '2027-05-15',
    rackLocation: 'Rack A-1, Shelf 1',
    purchasePrice: 2.5,
    sellingPrice: 3.0,
    wholesalePrice: 2.7,
    discount: 0,
    stock: 0, // প্রারম্ভিক স্টক শূন্য, দোকানদার পরে ইনওয়ার্ড করে চালু করবেন
    minStock: 50,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 10,
    stripPrice: 30,
    boxPrice: 290,
    requiresPrescription: false,
    description: 'জ্বর, তীব্র মাথাব্যথা, দাঁতব্যথা ও শারীরিক ব্যথানাশক জনপ্রিয় ওষুধ।',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_2',
    name: 'Napa 500mg Tablet',
    sku: 'MED-NAP-500',
    barcode: '890123456102',
    category: 'Pharmacy & Medicine',
    subCategory: 'জ্বর ও ব্যথানাশক (Fever & Pain)',
    brand: 'Beximco Pharma',
    manufacturer: 'Beximco Pharmaceuticals Ltd.',
    genericName: 'Paracetamol 500mg',
    dosageForm: 'Tablet',
    strength: '500mg',
    batchNumber: 'BEX-9104',
    expiryDate: '2027-08-20',
    rackLocation: 'Rack A-1, Shelf 1',
    purchasePrice: 1.0,
    sellingPrice: 1.2,
    wholesalePrice: 1.05,
    discount: 0,
    stock: 0,
    minStock: 100,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 50,
    stripPrice: 12,
    boxPrice: 580,
    requiresPrescription: false,
    description: 'সাধারণ জ্বর ও শরীর ব্যথায় নিরাপদ ও সর্বাধিক ব্যবহৃত প্যারাসিটামল।',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_3',
    name: 'Ace Plus Tablet',
    sku: 'MED-ACE-PLS',
    barcode: '890123456103',
    category: 'Pharmacy & Medicine',
    subCategory: 'জ্বর ও ব্যথানাশক (Fever & Pain)',
    brand: 'Square Pharma',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    genericName: 'Paracetamol + Caffeine (500mg + 65mg)',
    dosageForm: 'Tablet',
    strength: '500mg + 65mg',
    batchNumber: 'SQR-7712',
    expiryDate: '2027-09-10',
    rackLocation: 'Rack A-1, Shelf 2',
    purchasePrice: 2.5,
    sellingPrice: 3.0,
    wholesalePrice: 2.7,
    discount: 0,
    stock: 0,
    minStock: 50,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 10,
    stripPrice: 30,
    boxPrice: 290,
    requiresPrescription: false,
    description: 'স্কয়ার ফার্মাসিউটিক্যালসের প্যারাসিটামল ও ক্যাফেইন সংমিশ্রণ দ্রুত ব্যথানাশক।',
    image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_4',
    name: 'Seclo 20mg Capsule',
    sku: 'MED-SEC-20',
    barcode: '890123456104',
    category: 'Pharmacy & Medicine',
    subCategory: 'গ্যাস্ট্রিক ও অ্যাসিডিটি (Gastric & Acidity)',
    brand: 'Square Pharma',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    genericName: 'Omeprazole 20mg',
    dosageForm: 'Capsule',
    strength: '20mg',
    batchNumber: 'SQR-9901',
    expiryDate: '2027-11-15',
    rackLocation: 'Rack B-1, Shelf 1',
    purchasePrice: 5.6,
    sellingPrice: 7.0,
    wholesalePrice: 6.2,
    discount: 0,
    stock: 0,
    minStock: 40,
    unit: 'ক্যাপসুল (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 10,
    stripPrice: 70,
    boxPrice: 680,
    requiresPrescription: false,
    description: 'গ্যাস্ট্রিক আলসার, বুকজ্বালা ও পেটে গ্যাস নিরাময়ে দেশের শীর্ষ ওমিপ্রাজল ব্র্যান্ড।',
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_5',
    name: 'Sergel 20mg Capsule',
    sku: 'MED-SRG-20',
    barcode: '890123456105',
    category: 'Pharmacy & Medicine',
    subCategory: 'গ্যাস্ট্রিক ও অ্যাসিডিটি (Gastric & Acidity)',
    brand: 'Healthcare Pharma',
    manufacturer: 'Healthcare Pharmaceuticals Ltd.',
    genericName: 'Esomeprazole 20mg',
    dosageForm: 'Capsule',
    strength: '20mg',
    batchNumber: 'HPL-4421',
    expiryDate: '2027-10-30',
    rackLocation: 'Rack B-1, Shelf 2',
    purchasePrice: 5.8,
    sellingPrice: 7.0,
    wholesalePrice: 6.3,
    discount: 0,
    stock: 0,
    minStock: 40,
    unit: 'ক্যাপসুল (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 10,
    stripPrice: 70,
    boxPrice: 680,
    requiresPrescription: false,
    description: 'হেলথকেয়ার ফার্মার প্রিমিয়াম ইসোমিপ্রাজল, দীর্ঘস্থায়ী বুকজ্বালা ও অ্যাসিডিটি নিয়ন্ত্রণ করে।',
    image: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_6',
    name: 'Maxpro 20mg Capsule',
    sku: 'MED-MXP-20',
    barcode: '890123456106',
    category: 'Pharmacy & Medicine',
    subCategory: 'গ্যাস্ট্রিক ও অ্যাসিডিটি (Gastric & Acidity)',
    brand: 'Square Pharma',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    genericName: 'Esomeprazole 20mg',
    dosageForm: 'Capsule',
    strength: '20mg',
    batchNumber: 'SQR-6619',
    expiryDate: '2027-12-05',
    rackLocation: 'Rack B-1, Shelf 3',
    purchasePrice: 5.8,
    sellingPrice: 7.0,
    wholesalePrice: 6.3,
    discount: 0,
    stock: 0,
    minStock: 40,
    unit: 'ক্যাপসুল (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 10,
    stripPrice: 70,
    boxPrice: 680,
    requiresPrescription: false,
    description: 'স্কয়ারের জনপ্রিয় ইসোমিপ্রাজল ব্র্যান্ড, পেপটিক আলসার ও গ্যাস্ট্রোইসোফেজিয়াল রিফ্লাক্সে কার্যকর।',
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_7',
    name: 'Finix 20mg Tablet',
    sku: 'MED-FNX-20',
    barcode: '890123456107',
    category: 'Pharmacy & Medicine',
    subCategory: 'গ্যাস্ট্রিক ও অ্যাসিডিটি (Gastric & Acidity)',
    brand: 'Opsonin Pharma',
    manufacturer: 'Opsonin Pharma Ltd.',
    genericName: 'Rabeprazole Sodium 20mg',
    dosageForm: 'Tablet',
    strength: '20mg',
    batchNumber: 'OPS-3312',
    expiryDate: '2027-06-25',
    rackLocation: 'Rack B-2, Shelf 1',
    purchasePrice: 5.6,
    sellingPrice: 7.0,
    wholesalePrice: 6.2,
    discount: 0,
    stock: 0,
    minStock: 30,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 10,
    stripPrice: 70,
    boxPrice: 680,
    requiresPrescription: false,
    description: 'অপসোনিন ফার্মার বহুল প্রচলিত রেবিপ্রাজল ট্যাবলেট। দ্রুত গ্যাস্ট্রিক অ্যাসিড কমায়।',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_8',
    name: 'Pantonix 20mg Tablet',
    sku: 'MED-PTX-20',
    barcode: '890123456108',
    category: 'Pharmacy & Medicine',
    subCategory: 'গ্যাস্ট্রিক ও অ্যাসিডিটি (Gastric & Acidity)',
    brand: 'Incepta Pharma',
    manufacturer: 'Incepta Pharmaceuticals Ltd.',
    genericName: 'Pantoprazole 20mg',
    dosageForm: 'Tablet',
    strength: '20mg',
    batchNumber: 'INC-7821',
    expiryDate: '2027-07-15',
    rackLocation: 'Rack B-2, Shelf 2',
    purchasePrice: 5.8,
    sellingPrice: 7.0,
    wholesalePrice: 6.3,
    discount: 0,
    stock: 0,
    minStock: 30,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 10,
    stripPrice: 70,
    boxPrice: 680,
    requiresPrescription: false,
    description: 'ইনসেপ্টা ফার্মার জনপ্রিয় প্যান্টোপ্রাজল ট্যাবলেট। পেটের তীব্র গ্যাস ও জ্বালাপোড়ায় নির্দেশিত।',
    image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_9',
    name: 'Entacyd Plus Chewable Tablet',
    sku: 'MED-ENT-PLS',
    barcode: '890123456109',
    category: 'Pharmacy & Medicine',
    subCategory: 'অ্যান্টাসিড (Antacid)',
    brand: 'Square Pharma',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    genericName: 'Magaldrate + Simethicone',
    dosageForm: 'Tablet',
    strength: 'Chewable',
    batchNumber: 'SQR-4512',
    expiryDate: '2027-08-30',
    rackLocation: 'Rack B-2, Shelf 3',
    purchasePrice: 2.2,
    sellingPrice: 3.0,
    wholesalePrice: 2.5,
    discount: 0,
    stock: 0,
    minStock: 50,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 20,
    stripPrice: 30,
    boxPrice: 580,
    requiresPrescription: false,
    description: 'খাওয়ার সাথে সাথে চিবিয়ে খাওয়ার সুস্বাদু অ্যান্টাসিড। বুকজ্বালা সাথে সাথে নিরাময় করে।',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_10',
    name: 'Alatrol 10mg Tablet',
    sku: 'MED-ALA-10',
    barcode: '890123456110',
    category: 'Pharmacy & Medicine',
    subCategory: 'সর্দি ও অ্যালার্জি (Antihistamine)',
    brand: 'Square Pharma',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    genericName: 'Cetirizine Hydrochloride 10mg',
    dosageForm: 'Tablet',
    strength: '10mg',
    batchNumber: 'SQR-5544',
    expiryDate: '2027-11-20',
    rackLocation: 'Rack C-1, Shelf 1',
    purchasePrice: 2.8,
    sellingPrice: 3.5,
    wholesalePrice: 3.0,
    discount: 0,
    stock: 0,
    minStock: 40,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 10,
    stripPrice: 35,
    boxPrice: 340,
    requiresPrescription: false,
    description: 'এলার্জি, অনবরত হাঁচি, সর্দি, চোখ দিয়ে পানি পড়া ও ত্বকের চুলকানির দ্রুত সমাধান।',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_11',
    name: 'Fexo 120mg Tablet',
    sku: 'MED-FXO-120',
    barcode: '890123456111',
    category: 'Pharmacy & Medicine',
    subCategory: 'সর্দি ও অ্যালার্জি (Antihistamine)',
    brand: 'Square Pharma',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    genericName: 'Fexofenadine Hydrochloride 120mg',
    dosageForm: 'Tablet',
    strength: '120mg',
    batchNumber: 'SQR-8841',
    expiryDate: '2027-09-18',
    rackLocation: 'Rack C-1, Shelf 2',
    purchasePrice: 7.2,
    sellingPrice: 9.0,
    wholesalePrice: 7.8,
    discount: 0,
    stock: 0,
    minStock: 30,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 5,
    stripPrice: 90,
    boxPrice: 440,
    requiresPrescription: false,
    description: 'ঘুমহীন আধুনিক নন-সিডেটিং অ্যান্টিহিস্টামিন। সিজনাল অ্যালার্জি ও হাঁচির মহৌষধ।',
    image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_12',
    name: 'Telfast 120mg Tablet',
    sku: 'MED-TLF-120',
    barcode: '890123456112',
    category: 'Pharmacy & Medicine',
    subCategory: 'সর্দি ও অ্যালার্জি (Antihistamine)',
    brand: 'Sanofi',
    manufacturer: 'Sanofi Bangladesh Ltd.',
    genericName: 'Fexofenadine Hydrochloride 120mg',
    dosageForm: 'Tablet',
    strength: '120mg',
    batchNumber: 'SNF-1290',
    expiryDate: '2027-10-15',
    rackLocation: 'Rack C-1, Shelf 3',
    purchasePrice: 9.5,
    sellingPrice: 12.0,
    wholesalePrice: 10.5,
    discount: 0,
    stock: 0,
    minStock: 25,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 3,
    stripPrice: 120,
    boxPrice: 350,
    requiresPrescription: false,
    description: 'স্যানোফির অরিজিনাল রিসার্চ ব্র্যান্ড ফেক্সোফেনাডিন। আন্তর্জাতিক মানের অ্যালার্জি প্রতিষেধক।',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_13',
    name: 'Flamyd 400mg Tablet',
    sku: 'MED-FLM-400',
    barcode: '890123456113',
    category: 'Pharmacy & Medicine',
    subCategory: 'পেটের ওষুধ (Diarrhea & Protozoal)',
    brand: 'Square Pharma',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    genericName: 'Metronidazole 400mg',
    dosageForm: 'Tablet',
    strength: '400mg',
    batchNumber: 'SQR-3310',
    expiryDate: '2027-12-20',
    rackLocation: 'Rack C-2, Shelf 1',
    purchasePrice: 1.8,
    sellingPrice: 2.5,
    wholesalePrice: 2.0,
    discount: 0,
    stock: 0,
    minStock: 40,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 20,
    stripPrice: 25,
    boxPrice: 480,
    requiresPrescription: false,
    description: 'অ্যামিবিক আমাশয়, পেট খারাপ, দাঁতের ইনফেকশন ও ডায়রিয়া প্রতিরোধে অত্যন্ত কার্যকর।',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_14',
    name: 'Bizoran 5/20 Tablet',
    sku: 'MED-BZR-520',
    barcode: '890123456114',
    category: 'Pharmacy & Medicine',
    subCategory: 'প্রেসার ও কার্ডিয়াক (Hypertension)',
    brand: 'Square Pharma',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    genericName: 'Amlodipine 5mg + Olmesartan Medoxomil 20mg',
    dosageForm: 'Tablet',
    strength: '5mg + 20mg',
    batchNumber: 'SQR-2299',
    expiryDate: '2027-08-10',
    rackLocation: 'Rack D-1, Shelf 1',
    purchasePrice: 9.6,
    sellingPrice: 12.0,
    wholesalePrice: 10.5,
    discount: 0,
    stock: 0,
    minStock: 30,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 3,
    stripPrice: 120,
    boxPrice: 350,
    requiresPrescription: true,
    description: 'উচ্চ রক্তচাপ (হাই ব্লাড প্রেশার) নিয়ন্ত্রণে দেশের সর্বাধিক প্রেসক্রাইব করা কম্বিনেশন।',
    image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_15',
    name: 'Camlosart 5/20 Tablet',
    sku: 'MED-CML-520',
    barcode: '890123456115',
    category: 'Pharmacy & Medicine',
    subCategory: 'প্রেসার ও কার্ডিয়াক (Hypertension)',
    brand: 'Incepta Pharma',
    manufacturer: 'Incepta Pharmaceuticals Ltd.',
    genericName: 'Amlodipine 5mg + Olmesartan Medoxomil 20mg',
    dosageForm: 'Tablet',
    strength: '5mg + 20mg',
    batchNumber: 'INC-4412',
    expiryDate: '2027-09-25',
    rackLocation: 'Rack D-1, Shelf 2',
    purchasePrice: 9.6,
    sellingPrice: 12.0,
    wholesalePrice: 10.5,
    discount: 0,
    stock: 0,
    minStock: 30,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 3,
    stripPrice: 120,
    boxPrice: 350,
    requiresPrescription: true,
    description: 'ইনসেপ্টা ফার্মার নির্ভরযোগ্য উচ্চ রক্তচাপ নিয়ন্ত্রণকারী মেডিসিন।',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_16',
    name: 'Gluconor 500mg Tablet',
    sku: 'MED-GLC-500',
    barcode: '890123456116',
    category: 'Pharmacy & Medicine',
    subCategory: 'ডায়াবেটিস (Diabetes)',
    brand: 'Square Pharma',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    genericName: 'Metformin Hydrochloride 500mg',
    dosageForm: 'Tablet',
    strength: '500mg',
    batchNumber: 'SQR-7104',
    expiryDate: '2027-07-20',
    rackLocation: 'Rack D-2, Shelf 1',
    purchasePrice: 3.5,
    sellingPrice: 4.5,
    wholesalePrice: 3.8,
    discount: 0,
    stock: 0,
    minStock: 50,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 10,
    stripPrice: 45,
    boxPrice: 430,
    requiresPrescription: true,
    description: 'টাইপ-২ ডায়াবেটিস নিয়ন্ত্রণে রক্তের গ্লুকোজ হ্রাসকারী বহুল পরিচিত ওষুধ।',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_17',
    name: 'Secrin 2mg Tablet',
    sku: 'MED-SCR-2',
    barcode: '890123456117',
    category: 'Pharmacy & Medicine',
    subCategory: 'ডায়াবেটিস (Diabetes)',
    brand: 'Square Pharma',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    genericName: 'Glimepiride 2mg',
    dosageForm: 'Tablet',
    strength: '2mg',
    batchNumber: 'SQR-8832',
    expiryDate: '2027-11-12',
    rackLocation: 'Rack D-2, Shelf 2',
    purchasePrice: 6.4,
    sellingPrice: 8.0,
    wholesalePrice: 7.0,
    discount: 0,
    stock: 0,
    minStock: 30,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 5,
    stripPrice: 80,
    boxPrice: 390,
    requiresPrescription: true,
    description: 'ইনসুলিন ক্ষরণ বৃদ্ধিকারী ও রক্তের সুগার নিয়ন্ত্রণকারী প্রেসক্রিপশন ড্রাগ।',
    image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_18',
    name: 'Moxacil 500mg Capsule (Rx)',
    sku: 'MED-MOX-500',
    barcode: '890123456118',
    category: 'Pharmacy & Medicine',
    subCategory: 'অ্যান্টিবায়োটিক (Antibiotics)',
    brand: 'Square Pharma',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    genericName: 'Amoxicillin Trihydrate 500mg',
    dosageForm: 'Capsule',
    strength: '500mg',
    batchNumber: 'SQR-1102',
    expiryDate: '2027-06-15',
    rackLocation: 'Rack E-1, Shelf 1 (Rx Box)',
    purchasePrice: 6.2,
    sellingPrice: 7.75,
    wholesalePrice: 6.8,
    discount: 0,
    stock: 0,
    minStock: 30,
    unit: 'ক্যাপসুল (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 10,
    stripPrice: 77.5,
    boxPrice: 750,
    requiresPrescription: true,
    description: 'ব্যাকটেরিয়া জনিত ইনফেকশন, গলাব্যথা ও ব্রঙ্কাইটিসের ব্রড-স্পেকট্রাম অ্যান্টিবায়োটিক।',
    image: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_19',
    name: 'Zimax 500mg Tablet (Rx)',
    sku: 'MED-ZMX-500',
    barcode: '890123456119',
    category: 'Pharmacy & Medicine',
    subCategory: 'অ্যান্টিবায়োটিক (Antibiotics)',
    brand: 'Square Pharma',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    genericName: 'Azithromycin Dihydrate 500mg',
    dosageForm: 'Tablet',
    strength: '500mg',
    batchNumber: 'SQR-9941',
    expiryDate: '2027-08-15',
    rackLocation: 'Rack E-1, Shelf 2 (Rx Box)',
    purchasePrice: 28.0,
    sellingPrice: 35.0,
    wholesalePrice: 30.5,
    discount: 0,
    stock: 0,
    minStock: 20,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 3,
    stripsPerBox: 5,
    stripPrice: 105,
    boxPrice: 510,
    requiresPrescription: true,
    description: 'শ্বাসনালী, সাইনাস ও ফুসফুসের তীব্র সংক্রমণে বহুল ব্যবহৃত অ্যাজিথ্রোমাইসিন।',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_20',
    name: 'Monas 10mg Tablet',
    sku: 'MED-MNS-10',
    barcode: '890123456120',
    category: 'Pharmacy & Medicine',
    subCategory: 'শ্বাসকষ্ট ও অ্যাজমা (Respiratory)',
    brand: 'Acme Laboratories',
    manufacturer: 'The Acme Laboratories Ltd.',
    genericName: 'Montelukast Sodium 10mg',
    dosageForm: 'Tablet',
    strength: '10mg',
    batchNumber: 'ACM-6610',
    expiryDate: '2027-10-20',
    rackLocation: 'Rack E-2, Shelf 1',
    purchasePrice: 13.0,
    sellingPrice: 16.0,
    wholesalePrice: 14.0,
    discount: 0,
    stock: 0,
    minStock: 30,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 3,
    stripPrice: 160,
    boxPrice: 470,
    requiresPrescription: true,
    description: 'হাঁপানি (অ্যাজমা), শ্বাসনালীর টান ও ক্রনিক অ্যালার্জিক রাইনাইটিসে অত্যন্ত বিশ্বস্ত ওষুধ।',
    image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_21',
    name: 'Tusca Cough Syrup 100ml',
    sku: 'MED-TSC-100',
    barcode: '890123456121',
    category: 'Pharmacy & Medicine',
    subCategory: 'কাশির সিরাপ (Cough Syrup)',
    brand: 'Square Pharma',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    genericName: 'Dextromethorphan + Phenylephrine + Guaifenesin',
    dosageForm: 'Syrup',
    strength: '100ml',
    batchNumber: 'SQR-SYR-881',
    expiryDate: '2027-04-30',
    rackLocation: 'Rack F-1, Shelf 1',
    purchasePrice: 85.0,
    sellingPrice: 100.0,
    wholesalePrice: 90.0,
    discount: 0,
    stock: 0,
    minStock: 15,
    unit: 'বোতল (Bottle)',
    requiresPrescription: false,
    description: 'শুকনো কাশি, খুসখুসে কাশি ও গলায় কফ উপশমে জনপ্রিয় কাশির সিরাপ।',
    image: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_22',
    name: 'SMC Orsaline-N Sachet',
    sku: 'MED-SMC-ORS',
    barcode: '890123456122',
    category: 'Pharmacy & Medicine',
    subCategory: 'ওরাল স্যালাইন (Oral Saline)',
    brand: 'SMC',
    manufacturer: 'Social Marketing Company (SMC)',
    genericName: 'Oral Rehydration Salts (WHO Formula)',
    dosageForm: 'Powder',
    strength: 'Sachet (500ml prep)',
    batchNumber: 'SMC-5521',
    expiryDate: '2028-02-15',
    rackLocation: 'Rack F-2, Shelf 1',
    purchasePrice: 5.5,
    sellingPrice: 6.5,
    wholesalePrice: 5.8,
    discount: 0,
    stock: 0,
    minStock: 100,
    unit: 'প্যাকেট (Pkt)',
    requiresPrescription: false,
    description: 'ডায়রিয়া, বমি ও তীব্র গরমে শরীরের পানিশূন্যতা রোধে ডব্লিউএইচও ফর্মুলা স্যালাইন।',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_23',
    name: 'SMC Tasty Saline Sachet',
    sku: 'MED-SMC-TST',
    barcode: '890123456123',
    category: 'Pharmacy & Medicine',
    subCategory: 'ওরাল স্যালাইন (Oral Saline)',
    brand: 'SMC',
    manufacturer: 'Social Marketing Company (SMC)',
    genericName: 'Flavored Electrolyte Salts',
    dosageForm: 'Powder',
    strength: 'Orange Flavored Sachet',
    batchNumber: 'SMC-6601',
    expiryDate: '2028-01-20',
    rackLocation: 'Rack F-2, Shelf 1',
    purchasePrice: 6.0,
    sellingPrice: 7.0,
    wholesalePrice: 6.2,
    discount: 0,
    stock: 0,
    minStock: 100,
    unit: 'প্যাকেট (Pkt)',
    requiresPrescription: false,
    description: 'সুস্বাদু কমলার স্বাদযুক্ত রিহাইড্রেশন স্যালাইন। শিশু ও বড়দের দুর্বলতায় প্রিয় পছন্দ।',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_24',
    name: 'Calbo-D 500mg+200IU Tablet',
    sku: 'MED-CBD-500',
    barcode: '890123456124',
    category: 'Pharmacy & Medicine',
    subCategory: 'ক্যালসিয়াম ও ভিটামিন (Vitamins)',
    brand: 'Square Pharma',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    genericName: 'Calcium Carbonate + Vitamin D3',
    dosageForm: 'Tablet',
    strength: '500mg + 200IU',
    batchNumber: 'SQR-CLB-99',
    expiryDate: '2027-12-30',
    rackLocation: 'Rack G-1, Shelf 1',
    purchasePrice: 6.5,
    sellingPrice: 8.0,
    wholesalePrice: 7.0,
    discount: 0,
    stock: 0,
    minStock: 30,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 15,
    stripsPerBox: 2,
    stripPrice: 120,
    boxPrice: 235,
    requiresPrescription: false,
    description: 'হাড় মজবুত ও অস্টিওপোরোসিস প্রতিরোধে দেশের শীর্ষ ক্যালসিয়াম ও ভিটামিন ডি৩ সম্পূরক।',
    image: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_25',
    name: 'Aristovit B-50 Forte Tablet',
    sku: 'MED-ARS-B50',
    barcode: '890123456125',
    category: 'Pharmacy & Medicine',
    subCategory: 'ভিটামিন বি (Vitamin B Complex)',
    brand: 'Square Pharma',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    genericName: 'Vitamin B Complex Forte',
    dosageForm: 'Tablet',
    strength: 'Forte Formula',
    batchNumber: 'SQR-ARS-44',
    expiryDate: '2027-11-20',
    rackLocation: 'Rack G-1, Shelf 2',
    purchasePrice: 2.5,
    sellingPrice: 3.2,
    wholesalePrice: 2.8,
    discount: 0,
    stock: 0,
    minStock: 40,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 10,
    stripPrice: 32,
    boxPrice: 310,
    requiresPrescription: false,
    description: 'শারীরিক দুর্বলতা, মুখে ঘা ও স্নায়বিক বলবর্ধনে স্কয়ারের ভিটামিন বি-কমপ্লেক্স ফোর্ট।',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_26',
    name: 'Ceevit 250mg Chewable Tablet',
    sku: 'MED-CVT-250',
    barcode: '890123456126',
    category: 'Pharmacy & Medicine',
    subCategory: 'ভিটামিন সি (Vitamin C)',
    brand: 'Square Pharma',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    genericName: 'Ascorbic Acid (Vitamin C) 250mg',
    dosageForm: 'Tablet',
    strength: '250mg Chewable',
    batchNumber: 'SQR-CVT-10',
    expiryDate: '2027-10-15',
    rackLocation: 'Rack G-1, Shelf 3',
    purchasePrice: 1.8,
    sellingPrice: 2.25,
    wholesalePrice: 1.95,
    discount: 0,
    stock: 0,
    minStock: 60,
    unit: 'ট্যাবলেট (Pcs)',
    piecesPerStrip: 10,
    stripsPerBox: 24,
    stripPrice: 22.5,
    boxPrice: 530,
    requiresPrescription: false,
    description: 'রোগ প্রতিরোধ ক্ষমতা বৃদ্ধি ও স্কার্ভি প্রতিরোধে চিবিয়ে খাওয়ার সুস্বাদু ভিটামিন সি।',
    image: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_27',
    name: 'Savlon Antiseptic Liquid 100ml',
    sku: 'MED-SVL-100',
    barcode: '890123456127',
    category: 'Pharmacy & Medicine',
    subCategory: 'ফার্স্ট এইড ও অ্যান্টিসেপ্টিক (First Aid)',
    brand: 'ACI Limited',
    manufacturer: 'ACI Pharmaceuticals & Consumer Ltd.',
    genericName: 'Chlorhexidine Gluconate + Cetrimide Solution',
    dosageForm: 'Liquid',
    strength: '100ml Bottle',
    batchNumber: 'ACI-SVL-88',
    expiryDate: '2028-03-31',
    rackLocation: 'Rack H-1, Shelf 1',
    purchasePrice: 52.0,
    sellingPrice: 60.0,
    wholesalePrice: 54.0,
    discount: 0,
    stock: 0,
    minStock: 20,
    unit: 'বোতল (Bottle)',
    requiresPrescription: false,
    description: 'কাটা-ছেঁড়া, ক্ষত পরিষ্কার ও প্রাথমিক চিকিৎসার জন্য বিশ্বস্ত স্যাভলন অ্যান্টিসেপ্টিক।',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_28',
    name: 'Dettol Antiseptic Liquid 110ml',
    sku: 'MED-DTL-110',
    barcode: '890123456128',
    category: 'Pharmacy & Medicine',
    subCategory: 'ফার্স্ট এইড ও অ্যান্টিসেপ্টিক (First Aid)',
    brand: 'Reckitt',
    manufacturer: 'Reckitt Benckiser Bangladesh PLC',
    genericName: 'Chloroxylenol 4.8% w/v',
    dosageForm: 'Liquid',
    strength: '110ml Bottle',
    batchNumber: 'RB-DTL-310',
    expiryDate: '2028-04-15',
    rackLocation: 'Rack H-1, Shelf 2',
    purchasePrice: 65.0,
    sellingPrice: 75.0,
    wholesalePrice: 68.0,
    discount: 0,
    stock: 0,
    minStock: 20,
    unit: 'বোতল (Bottle)',
    requiresPrescription: false,
    description: 'জীবাণুনাশক অ্যান্টিসেপ্টিক লিকুইড। ফার্স্ট এইড ও ব্যক্তিগত সুরক্ষায় বহুল পরিচিত।',
    image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_29',
    name: 'Hexisol Hand Rub 250ml',
    sku: 'MED-HXS-250',
    barcode: '890123456129',
    category: 'Pharmacy & Medicine',
    subCategory: 'হ্যান্ড স্যানিটাইজার (Hand Rub)',
    brand: 'ACI Limited',
    manufacturer: 'ACI HealthCare Limited',
    genericName: 'Chlorhexidine Gluconate 0.5% in 70% Isopropyl Alcohol',
    dosageForm: 'Liquid',
    strength: '250ml Dispenser',
    batchNumber: 'ACI-HXS-91',
    expiryDate: '2028-05-10',
    rackLocation: 'Rack H-1, Shelf 3',
    purchasePrice: 110.0,
    sellingPrice: 130.0,
    wholesalePrice: 116.0,
    discount: 0,
    stock: 0,
    minStock: 15,
    unit: 'বোতল (Bottle)',
    requiresPrescription: false,
    description: 'হাসপাতাল গ্রেড হ্যান্ড স্যানিটাইজার ও হ্যান্ড স্ক্রাব। দ্রুত ৯৯.৯% জীবাণু ধ্বংস করে।',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_30',
    name: 'Viodin 10% Solution 100ml',
    sku: 'MED-VDN-100',
    barcode: '890123456130',
    category: 'Pharmacy & Medicine',
    subCategory: 'অ্যান্টিসেপ্টিক ও ড্রেসিং (Antiseptic)',
    brand: 'Square Pharma',
    manufacturer: 'Square Pharmaceuticals Ltd.',
    genericName: 'Povidone Iodine 10% Antiseptic Solution',
    dosageForm: 'Liquid',
    strength: '100ml Bottle',
    batchNumber: 'SQR-VDN-12',
    expiryDate: '2028-02-28',
    rackLocation: 'Rack H-2, Shelf 1',
    purchasePrice: 72.0,
    sellingPrice: 85.0,
    wholesalePrice: 76.0,
    discount: 0,
    stock: 0,
    minStock: 15,
    unit: 'বোতল (Bottle)',
    requiresPrescription: false,
    description: 'পোভিডোন আয়োডিন সলিউশন। ক্ষতস্থান ওয়াশ ও ড্রেসিংয়ের ব্রড স্পেকট্রাম অ্যান্টিসেপ্টিক।',
    image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_31',
    name: 'Digital Clinical Thermometer',
    sku: 'MED-THM-DIG',
    barcode: '890123456131',
    category: 'Pharmacy & Medicine',
    subCategory: 'মেডিকেল ডিভাইস (Medical Device)',
    brand: 'Omron Healthcare',
    manufacturer: 'Omron Healthcare Ltd.',
    genericName: 'Electronic Clinical Fever Thermometer',
    dosageForm: 'Device',
    strength: 'Waterproof Quick Read',
    batchNumber: 'OMR-THM-80',
    expiryDate: '2030-12-31',
    rackLocation: 'Rack H-3, Shelf 1',
    purchasePrice: 160.0,
    sellingPrice: 250.0,
    wholesalePrice: 190.0,
    discount: 0,
    stock: 0,
    minStock: 10,
    unit: 'পিস (Pcs)',
    requiresPrescription: false,
    description: 'নির্ভুল জ্বর পরিমাপের ডিজিটাল ওয়াটারপ্রুফ থার্মোমিটার। দ্রুত বিপ অ্যালার্ট সুবিধা সম্পন্ন।',
    image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
  {
    id: 'med_32',
    name: 'Accu-Chek Active Blood Glucose Monitor Kit',
    sku: 'MED-GLU-MTR',
    barcode: '890123456132',
    category: 'Pharmacy & Medicine',
    subCategory: 'ডায়াবেটিস ডিভাইস (Medical Device)',
    brand: 'Roche Diabetes Care',
    manufacturer: 'Roche Diabetes Care GmbH',
    genericName: 'Blood Glucose Meter with 10 Strips & Lancets',
    dosageForm: 'Device',
    strength: 'Complete Starter Kit',
    batchNumber: 'RCH-GLU-99',
    expiryDate: '2029-12-31',
    rackLocation: 'Rack H-3, Shelf 2',
    purchasePrice: 1450.0,
    sellingPrice: 1850.0,
    wholesalePrice: 1600.0,
    discount: 0,
    stock: 0,
    minStock: 5,
    unit: 'সেট (Set)',
    requiresPrescription: false,
    description: 'ঘরে বসে রক্তে গ্লুকোজ মাপার বিশ্বখ্যাত আকু-চেক অ্যাক্টিভ মিটার কিট (১০টি স্ট্রিপ ও ল্যানসেট সহ)।',
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-03-01',
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust_1',
    name: 'মেহেদী হাসান শুভ',
    mobile: '01812345678',
    alternateMobile: '01511223344',
    email: 'shuvo@gmail.com',
    address: 'বাড়ি ১২, রোড ৪, ধানমন্ডি, ঢাকা',
    customerType: 'Wholesale',
    tier: 'Gold',
    creditLimit: 15000,
    creditTermDays: 15,
    isCreditLocked: false,
    guarantorName: 'হাজী শামসুল হক',
    guarantorMobile: '01711223399',
    guarantorRelation: 'মামা (ব্যবসা স্বত্বাধিকারী)',
    tags: ['বিশ্বস্ত', 'পাইকারি', 'নিয়মিত'],
    totalPurchase: 18500,
    totalPaid: 15500,
    totalDue: 3000,
    oldestDueDays: 12,
    promiseDate: '2026-09-20',
    ordersCount: 8,
    lastOrderDate: '2026-03-08',
    riskLevel: 'Low',
    deliverySuccessRate: 95,
    ordersDelivered: 8,
    ordersCancelled: 0,
    ordersReturned: 0,
    notes: 'বিশ্বস্ত নিয়মিত পাইকারি গ্রাহক, প্রতি মাসে গ্যাজেট সামগ্রী ক্রয় করেন।',
    createdAt: '2025-11-10',
    ledger: [
      {
        id: 'led_101',
        date: '2026-03-08',
        type: 'Sale',
        referenceId: 'SX-POS-9812',
        debit: 5000,
        credit: 2000,
        balance: 3000,
        method: 'bKash',
        notes: 'স্মার্টওয়াচ ও এক্সেসরিজ পাইকারি ক্রয় (বাকি: ৳৩,০০০)',
      },
      {
        id: 'led_102',
        date: '2026-02-25',
        type: 'Due Collection',
        referenceId: 'MR-552101',
        debit: 0,
        credit: 4500,
        balance: 0,
        method: 'Cash',
        notes: 'পূর্ববর্তী সম্পূর্ণ বকেয়া আদায়',
      },
      {
        id: 'led_103',
        date: '2026-02-15',
        type: 'Sale',
        referenceId: 'SX-POS-9201',
        debit: 7500,
        credit: 3000,
        balance: 4500,
        method: 'Cash',
        notes: 'পাওয়ার ব্যাংক ও চার্জার অর্ডার',
      },
    ],
  },
  {
    id: 'cust_2',
    name: 'ফারহানা ইয়াসমিন',
    mobile: '01798765432',
    email: 'farhana@yahoo.com',
    address: 'ফ্ল্যাট ৪বি, সেকশন ৭, উত্তরা, ঢাকা',
    customerType: 'Retail',
    tier: 'Silver',
    creditLimit: 5000,
    creditTermDays: 7,
    isCreditLocked: false,
    totalPurchase: 9200,
    totalPaid: 9200,
    totalDue: 0,
    oldestDueDays: 0,
    ordersCount: 4,
    lastOrderDate: '2026-03-07',
    riskLevel: 'Low',
    deliverySuccessRate: 100,
    ordersDelivered: 4,
    ordersCancelled: 0,
    ordersReturned: 0,
    notes: 'অনলাইন স্টোর থেকে নিয়মিত অর্ডার প্রদান করেন, দ্রুত পরিশোধকারী।',
    createdAt: '2025-12-05',
    ledger: [
      {
        id: 'led_201',
        date: '2026-03-07',
        type: 'Sale',
        referenceId: 'SX-POS-9650',
        debit: 2200,
        credit: 2200,
        balance: 0,
        method: 'bKash',
        notes: 'সম্পূর্ণ পরিশোধিত বিক্রয়',
      },
    ],
  },
  {
    id: 'cust_3',
    name: 'কামরুল ইসলাম রনি',
    mobile: '01911223344',
    email: 'kamrul@gmail.com',
    address: 'জিইসি মোড়, চট্টগ্রাম',
    customerType: 'Retail',
    tier: 'General',
    creditLimit: 3000,
    creditTermDays: 10,
    isCreditLocked: false,
    totalPurchase: 6400,
    totalPaid: 4400,
    totalDue: 2000,
    oldestDueDays: 45,
    promiseDate: '2026-09-18',
    reminderNotes: 'ফোনে কথা হয়েছে, ১৮ তারিখে টাকা দেওয়ার কথা বলেছেন।',
    ordersCount: 5,
    lastOrderDate: '2026-03-05',
    riskLevel: 'Medium',
    deliverySuccessRate: 60,
    ordersDelivered: 3,
    ordersCancelled: 1,
    ordersReturned: 1,
    notes: 'কুরিয়ারে মাঝেমাঝে পার্সেল রিসিভ করতে বিলম্ব করেন।',
    createdAt: '2026-01-12',
    ledger: [
      {
        id: 'led_301',
        date: '2026-03-05',
        type: 'Sale',
        referenceId: 'SX-POS-9420',
        debit: 3400,
        credit: 1400,
        balance: 2000,
        method: 'Nagad',
        notes: 'ব্লুটুথ হেডফোন (বকেয়া: ৳২,০০০)',
      },
    ],
  },
  {
    id: 'cust_4',
    name: 'জাহিদুল ইসলাম',
    mobile: '01655443322',
    address: 'আগ্রাবাদ বাণিজ্যিক এলাকা, চট্টগ্রাম',
    customerType: 'Corporate',
    tier: 'General',
    creditLimit: 3000,
    creditTermDays: 15,
    isCreditLocked: true, // Over limit alert!
    guarantorName: 'রফিকুল ইসলাম',
    guarantorMobile: '01811223388',
    guarantorRelation: 'ব্যবসায়িক পার্টনার',
    tags: ['ঝুঁকিপূর্ণ', 'কর্পোরেট', 'খেলাপি'],
    totalPurchase: 8200,
    totalPaid: 3200,
    totalDue: 5000,
    oldestDueDays: 95, // 90+ days overdue!
    promiseDate: '2026-09-10',
    reminderNotes: 'তারিখ পার হয়ে গেছে, তাগাদা দেওয়া প্রয়োজন।',
    ordersCount: 3,
    lastOrderDate: '2026-03-02',
    riskLevel: 'High',
    deliverySuccessRate: 33,
    ordersDelivered: 1,
    ordersCancelled: 1,
    ordersReturned: 1,
    notes: 'বকেয়া সীমা ছাড়িয়েছে ও ৯০ দিনের বেশি বকেয়া। নতুন বাকি বিক্রয় লক করা আছে।',
    createdAt: '2026-01-20',
    installmentPlans: [
      {
        id: 'plan_mock_1',
        customerId: 'cust_4',
        customerName: 'জাহিদুল ইসলাম',
        customerMobile: '01655443322',
        totalDueAmount: 5000,
        numberOfInstallments: 3,
        intervalDays: 15,
        startDate: '2026-09-01',
        status: 'Active',
        createdAt: '2026-09-01',
        notes: '৩টি কিস্তিতে পরিশোধের চুক্তি',
        installments: [
          {
            id: 'inst_m1_1',
            installmentNo: 1,
            amount: 1666,
            dueDate: '2026-09-01',
            status: 'Paid',
            paidDate: '2026-09-02',
            paidAmount: 1666,
            paymentMethod: 'Cash',
            receiptNumber: 'EMI-REC-881201',
          },
          {
            id: 'inst_m1_2',
            installmentNo: 2,
            amount: 1666,
            dueDate: '2026-09-16',
            status: 'Overdue',
          },
          {
            id: 'inst_m1_3',
            installmentNo: 3,
            amount: 1668,
            dueDate: '2026-10-01',
            status: 'Pending',
          },
        ],
      },
    ],
    ledger: [
      {
        id: 'led_401',
        date: '2026-02-10',
        type: 'Sale',
        referenceId: 'SX-POS-8910',
        debit: 5000,
        credit: 0,
        balance: 5000,
        method: 'Cash',
        notes: 'অফিস ক্যাবল ও সরঞ্জাম (বকেয়া)',
      },
    ],
  },
  {
    id: 'cust_5',
    name: 'ওয়াক-ইন কাস্টমার (কাউন্টার)',
    mobile: '01700000000',
    address: 'কাউন্টার সেল (নগদ খদ্দের)',
    customerType: 'Retail',
    tier: 'Platinum',
    creditLimit: 0,
    creditTermDays: 0,
    totalPurchase: 45000,
    totalPaid: 45000,
    totalDue: 0,
    oldestDueDays: 0,
    ordersCount: 32,
    lastOrderDate: '2026-03-09',
    riskLevel: 'Low',
    deliverySuccessRate: 100,
    ordersDelivered: 32,
    ordersCancelled: 0,
    ordersReturned: 0,
    notes: 'সাধারণ নগদ ক্রেতা।',
    createdAt: '2025-10-01',
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup_1',
    name: 'রহিম উল্লাহ চৌধুরী',
    companyName: 'গ্যাজেট অ্যান্ড টেক বিডি লিমিটেড',
    mobile: '01712334455',
    email: 'info@gadgetbd.com',
    address: 'মোতালিব প্লাজা, হাতিরপুল, ঢাকা',
    totalPurchase: 145000,
    totalPaid: 125000,
    totalPayable: 20000,
    lastPurchaseDate: '2026-03-02',
    createdAt: '2025-08-15',
  },
  {
    id: 'sup_2',
    name: 'আরিফ হোসেন',
    companyName: 'স্মার্ট ইম্পোর্ট হাব',
    mobile: '01899887766',
    email: 'arif@smarthub.com.bd',
    address: 'নবাবপুর রোড, পুরান ঢাকা',
    totalPurchase: 85000,
    totalPaid: 75000,
    totalPayable: 10000,
    lastPurchaseDate: '2026-02-24',
    createdAt: '2025-09-20',
  },
  {
    id: 'sup_3',
    name: 'নাজমুল করিম',
    companyName: 'লাইফস্টাইল এক্সেসরিজ সাপ্লাই',
    mobile: '01922334455',
    address: 'নিউ মার্কেট, ঢাকা',
    totalPurchase: 52000,
    totalPaid: 52000,
    totalPayable: 0,
    lastPurchaseDate: '2026-02-15',
    createdAt: '2025-10-10',
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ord_1001',
    orderNumber: 'SX-260309-01',
    customerId: 'cust_1',
    customerName: 'মেহেদী হাসান শুভ',
    customerMobile: '01812345678',
    customerAddress: 'বাড়ি ১২, রোড ৪, ধানমন্ডি, ঢাকা',
    items: [
      {
        productId: 'prod_1',
        productName: 'Wireless Bluetooth Earbuds Pro (ANC)',
        quantity: 1,
        unitPrice: 2500,
        total: 2500,
      },
      {
        productId: 'prod_2',
        productName: '20W PD Fast Charger Adapter (Type-C)',
        quantity: 1,
        unitPrice: 700,
        total: 700,
      },
    ],
    subtotal: 3200,
    discount: 100,
    deliveryCharge: 70,
    totalAmount: 3170,
    paidAmount: 3170,
    dueAmount: 0,
    paymentMethod: 'bKash',
    paymentStatus: 'Paid',
    orderStatus: 'Delivered',
    channel: 'Online Store',
    courierName: 'Steadfast',
    courierTrackingCode: 'SF92837492',
    createdAt: '2026-03-09T14:30:00',
  },
  {
    id: 'ord_1002',
    orderNumber: 'SX-260309-02',
    customerId: 'cust_2',
    customerName: 'ফারহানা ইয়াসমিন',
    customerMobile: '01798765432',
    customerAddress: 'ফ্ল্যাট ৪বি, সেকশন ৭, উত্তরা, ঢাকা',
    items: [
      {
        productId: 'prod_4',
        productName: 'Smart Watch Series 9 AMOLED Display',
        quantity: 1,
        unitPrice: 3000,
        total: 3000,
      },
    ],
    subtotal: 3000,
    discount: 0,
    deliveryCharge: 70,
    totalAmount: 3070,
    paidAmount: 3070,
    dueAmount: 0,
    paymentMethod: 'Nagad',
    paymentStatus: 'Paid',
    orderStatus: 'Shipped',
    channel: 'Landing Page',
    courierName: 'Pathao',
    courierTrackingCode: 'PT-8839201',
    createdAt: '2026-03-09T11:15:00',
  },
  {
    id: 'ord_1003',
    orderNumber: 'SX-260309-03',
    customerId: 'cust_5',
    customerName: 'ওয়াক-ইন কাস্টমার',
    customerMobile: '01700000000',
    customerAddress: 'কাউন্টার',
    items: [
      {
        productId: 'prod_2',
        productName: '20W PD Fast Charger Adapter (Type-C)',
        quantity: 2,
        unitPrice: 700,
        total: 1400,
      },
    ],
    subtotal: 1400,
    discount: 50,
    deliveryCharge: 0,
    totalAmount: 1350,
    paidAmount: 1350,
    dueAmount: 0,
    paymentMethod: 'Cash',
    paymentStatus: 'Paid',
    orderStatus: 'Delivered',
    channel: 'POS',
    createdAt: '2026-03-09T16:20:00',
  },
  {
    id: 'ord_1004',
    orderNumber: 'SX-260308-01',
    customerId: 'cust_3',
    customerName: 'কামরুল ইসলাম রনি',
    customerMobile: '01911223344',
    customerAddress: 'জিইসি মোড়, চট্টগ্রাম',
    items: [
      {
        productId: 'prod_3',
        productName: '10,000mAh Magnetic Power Bank with Stand',
        quantity: 1,
        unitPrice: 1750,
        total: 1750,
      },
    ],
    subtotal: 1750,
    discount: 0,
    deliveryCharge: 130,
    totalAmount: 1880,
    paidAmount: 500,
    dueAmount: 1380,
    paymentMethod: 'Cash',
    paymentStatus: 'Partially Paid',
    orderStatus: 'Courier Assigned',
    channel: 'Online Store',
    courierName: 'RedX',
    courierTrackingCode: 'RDX-994821',
    createdAt: '2026-03-08T18:40:00',
  },
  {
    id: 'ord_1005',
    orderNumber: 'SX-260308-02',
    customerId: 'cust_4',
    customerName: 'জাহিদুল ইসলাম',
    customerMobile: '01655443322',
    customerAddress: 'আগ্রাবাদ, চট্টগ্রাম',
    items: [
      {
        productId: 'prod_7',
        productName: 'RGB Mechanical Gaming Keyboard (Blue Switch)',
        quantity: 1,
        unitPrice: 2700,
        total: 2700,
      },
    ],
    subtotal: 2700,
    discount: 0,
    deliveryCharge: 130,
    totalAmount: 2830,
    paidAmount: 0,
    dueAmount: 2830,
    paymentMethod: 'Cash',
    paymentStatus: 'Pending',
    orderStatus: 'New',
    channel: 'Online Store',
    createdAt: '2026-03-08T21:05:00',
  },
];

export const initialIncompleteOrders: IncompleteOrder[] = [
  {
    id: 'inc_1',
    customerName: 'আসিফ রায়হান',
    customerMobile: '01755667788',
    productName: 'Wireless Bluetooth Earbuds Pro (ANC)',
    quantity: 1,
    amount: 2570,
    source: 'Landing Page',
    createdAt: '2026-03-09T18:10:00',
    status: 'Abandoned',
    notes: 'চেকআউট ফর্ম পূরণ করার সময় ড্রপ করেছে।',
  },
  {
    id: 'inc_2',
    customerName: 'নুসরাত জাহান',
    customerMobile: '01877665544',
    productName: 'Smart Watch Series 9 AMOLED Display',
    quantity: 1,
    amount: 3070,
    source: 'Online Store',
    createdAt: '2026-03-09T15:45:00',
    status: 'Followed-Up',
    notes: 'ফোন করে ডেলিভারি চার্জ ডিসকাউন্ট চেয়েছেন, বিবেচনাধীন।',
  },
  {
    id: 'inc_3',
    customerName: 'মাহমুদ আলম',
    customerMobile: '01933445566',
    productName: 'RGB Mechanical Gaming Keyboard (Blue Switch)',
    quantity: 1,
    amount: 2830,
    source: 'Landing Page',
    createdAt: '2026-03-08T19:30:00',
    status: 'Abandoned',
    notes: 'পেমেন্ট গেটওয়ে পেজে ফেরত যাননি।',
  },
];

export const initialPurchases: Purchase[] = [
  {
    id: 'pur_1',
    purchaseNumber: 'PO-260302-01',
    supplierId: 'sup_1',
    supplierName: 'গ্যাজেট অ্যান্ড টেক বিডি লিমিটেড',
    items: [
      {
        productId: 'prod_1',
        productName: 'Wireless Bluetooth Earbuds Pro (ANC)',
        quantity: 20,
        purchasePrice: 1800,
        total: 36000,
      },
      {
        productId: 'prod_2',
        productName: '20W PD Fast Charger Adapter (Type-C)',
        quantity: 40,
        purchasePrice: 450,
        total: 18000,
      },
    ],
    totalAmount: 54000,
    paidAmount: 34000,
    dueAmount: 20000,
    paymentMethod: 'Bank',
    purchaseDate: '2026-03-02',
    notes: 'মার্চ মাসের নিয়মিত স্টক রিস্টকিং ইনভয়েস।',
  },
  {
    id: 'pur_2',
    purchaseNumber: 'PO-260224-02',
    supplierId: 'sup_2',
    supplierName: 'স্মার্ট ইম্পোর্ট হাব',
    items: [
      {
        productId: 'prod_4',
        productName: 'Smart Watch Series 9 AMOLED Display',
        quantity: 15,
        purchasePrice: 2100,
        total: 31500,
      },
    ],
    totalAmount: 31500,
    paidAmount: 21500,
    dueAmount: 10000,
    paymentMethod: 'bKash',
    purchaseDate: '2026-02-24',
    notes: 'স্মার্টওয়াচ নতুন ব্যাচ।',
  },
];

export const initialStockMovements: StockMovement[] = [
  {
    id: 'sm_1',
    productId: 'prod_1',
    productName: 'Wireless Bluetooth Earbuds Pro (ANC)',
    type: 'IN',
    quantity: 20,
    previousStock: 5,
    newStock: 25,
    reason: 'Purchase PO-260302-01 থেকে ইন হয়েছে',
    createdAt: '2026-03-02 11:30',
  },
  {
    id: 'sm_2',
    productId: 'prod_1',
    productName: 'Wireless Bluetooth Earbuds Pro (ANC)',
    type: 'SALE',
    quantity: 1,
    previousStock: 25,
    newStock: 24,
    reason: 'Order SX-260309-01 এর মাধ্যমে বিক্রয়',
    createdAt: '2026-03-09 14:30',
  },
  {
    id: 'sm_3',
    productId: 'prod_3',
    productName: '10,000mAh Magnetic Power Bank with Stand',
    type: 'ADJUSTMENT',
    quantity: -1,
    previousStock: 5,
    newStock: 4,
    reason: 'কাউন্টার ডিসপ্লে ড্যামেজ রাইট-অফ',
    createdAt: '2026-03-08 17:00',
  },
];

export const initialPayments: PaymentTransaction[] = [
  {
    id: 'pay_1',
    transactionId: 'TXN-90281',
    orderId: 'ord_1001',
    customerOrSupplierName: 'মেহেদী হাসান শুভ',
    type: 'Customer Payment',
    amount: 3170,
    method: 'bKash',
    status: 'Paid',
    date: '2026-03-09 14:30',
  },
  {
    id: 'pay_2',
    transactionId: 'TXN-90282',
    orderId: 'ord_1002',
    customerOrSupplierName: 'ফারহানা ইয়াসমিন',
    type: 'Customer Payment',
    amount: 3070,
    method: 'Nagad',
    status: 'Paid',
    date: '2026-03-09 11:15',
  },
  {
    id: 'pay_3',
    transactionId: 'TXN-90283',
    orderId: 'ord_1003',
    customerOrSupplierName: 'ওয়াক-ইন কাস্টমার',
    type: 'Customer Payment',
    amount: 1350,
    method: 'Cash',
    status: 'Paid',
    date: '2026-03-09 16:20',
  },
  {
    id: 'pay_4',
    transactionId: 'TXN-90284',
    customerOrSupplierName: 'গ্যাজেট অ্যান্ড টেক বিডি লিমিটেড',
    type: 'Supplier Payment',
    amount: 15000,
    method: 'Bank',
    status: 'Paid',
    date: '2026-03-05 12:00',
    notes: 'বকেয়া আংশিক পরিশোধ',
  },
  {
    id: 'pay_5',
    transactionId: 'TXN-90285',
    orderId: 'ord_1004',
    customerOrSupplierName: 'কামরুল ইসলাম রনি',
    type: 'Due Collection',
    amount: 500,
    method: 'Cash',
    status: 'Partially Paid',
    date: '2026-03-08 18:40',
  },
];

export const initialLandingPages: LandingPage[] = [
  {
    id: 'lp_1',
    title: 'ANC ওয়্যারলেস এয়ারবাডস প্রিমিয়াম সেল পেজ',
    slug: 'anc-earbuds-pro-offer',
    template: 'Mobile',
    headline: 'অরিজিনাল নয়েজ ক্যান্সেলেশন এয়ারবাডস - সীমিত সময়ের মেগা অফার!',
    subheadline: '৩০ ঘণ্টার টানা ব্যাকআপ, ক্রিস্টাল ক্লিয়ার কলিং ও ৩ দিনের ফ্রি রিপ্লেসমেন্ট গ্যারান্টি।',
    productName: 'Wireless Bluetooth Earbuds Pro (ANC)',
    regularPrice: 2800,
    offerPrice: 2500,
    primaryColor: '#059669',
    isPublished: true,
    viewsCount: 1420,
    ordersCount: 38,
    sections: {
      hero: true,
      product: true,
      offer: true,
      features: true,
      benefits: true,
      reviews: true,
      faq: true,
      delivery: true,
      orderForm: true,
      cta: true,
      footer: true,
    },
    featuresList: [
      'সরাসরি ANC সাউন্ড আইসোলেশন ও ডিপ বেস',
      'আইফোন ও অ্যান্ড্রয়েড উভয়ের সাথে দ্রুত পেয়ারিং',
      'সারাদেশে হোম ডেলিভারি ও পার্সেল দেখে পেমেন্ট সুবিধা',
    ],
    createdAt: '2026-02-28',
  },
  {
    id: 'lp_2',
    title: 'AMOLED স্মার্টওয়াচ সিরিজ ৯ ক্যাম্পেইন',
    slug: 'smartwatch-series-9-deal',
    template: 'Electronics',
    headline: 'আল্ট্রা স্লিম বেজেল অ্যামোলেড স্মার্টওয়াচ - ফ্ল্যাশ ডিসকাউন্ট!',
    subheadline: 'ব্লুটুথ কলিং ও ফিটনেস ট্র্যাকিং সম্পন্ন আধুনিক স্মার্টওয়াচ।',
    productName: 'Smart Watch Series 9 AMOLED Display',
    regularPrice: 3500,
    offerPrice: 3000,
    primaryColor: '#2563eb',
    isPublished: true,
    viewsCount: 980,
    ordersCount: 22,
    sections: {
      hero: true,
      product: true,
      offer: true,
      features: true,
      benefits: true,
      reviews: true,
      faq: true,
      delivery: true,
      orderForm: true,
      cta: true,
      footer: true,
    },
    featuresList: [
      'অলওয়েজ অন ডিসপ্লে মোড',
      'আইপি৬৮ ওয়াটার অ্যান্ড ডাস্ট রেসিস্ট্যান্ট',
      'অরিজিনাল ব্র্যান্ড ওয়ারেন্টি',
    ],
    createdAt: '2026-03-01',
  },
];

export const initialCourierOrders: CourierOrder[] = [
  {
    id: 'courier_1',
    orderId: 'ord_1001',
    orderNumber: 'SX-260309-01',
    customerName: 'মেহেদী হাসান শুভ',
    customerMobile: '01812345678',
    courierProvider: 'Steadfast',
    trackingNumber: 'SF92837492',
    codAmount: 0,
    deliveryStatus: 'Delivered',
    lastUpdated: '2026-03-09 18:00',
  },
  {
    id: 'courier_2',
    orderId: 'ord_1002',
    orderNumber: 'SX-260309-02',
    customerName: 'ফারহানা ইয়াসমিন',
    customerMobile: '01798765432',
    courierProvider: 'Pathao',
    trackingNumber: 'PT-8839201',
    codAmount: 0,
    deliveryStatus: 'Out for Delivery',
    lastUpdated: '2026-03-09 14:00',
  },
  {
    id: 'courier_3',
    orderId: 'ord_1004',
    orderNumber: 'SX-260308-01',
    customerName: 'কামরুল ইসলাম রনি',
    customerMobile: '01911223344',
    courierProvider: 'RedX',
    trackingNumber: 'RDX-994821',
    codAmount: 1380,
    deliveryStatus: 'In Transit',
    lastUpdated: '2026-03-09 09:30',
  },
];

export const initialBlockedEntities: BlockedEntity[] = [
  {
    id: 'blk_1',
    type: 'Mobile',
    value: '01999887711',
    reason: 'একটানা ৩ বার ফেক অর্ডার করে পার্সেল রিসিভ করেনি',
    addedBy: 'তানভীর আহমেদ',
    createdAt: '2026-02-14',
  },
  {
    id: 'blk_2',
    type: 'IP',
    value: '103.145.72.18',
    reason: 'বট রিকুয়েস্ট ও বাল্ক স্প্যাম ফর্ম সাবমিট',
    addedBy: 'সিস্টেম অটোমেটিক সিকিউরিটি',
    createdAt: '2026-02-20',
  },
];

export const initialNotificationSettings: NotificationSettings = {
  newOrderSms: true,
  orderConfirmationSms: true,
  paymentReceivedSms: true,
  shipmentSms: true,
  deliverySms: true,
  dueReminderSms: true,
  whatsappEnabled: true,
};

export const initialFacebookSettings: FacebookPixelSettings = {
  pixelId: '827364519283741',
  accessToken: 'EAAG827364519283741MetaGraphApiToken',
  testEventCode: 'TEST88219',
  conversionApiStatus: true,
  trackingActive: true,
  trackPageView: true,
  trackViewContent: true,
  trackAddToCart: true,
  trackInitiateCheckout: true,
  trackPurchase: true,
};

export const initialBusinesses = [
  {
    id: 'shop_101',
    name: 'স্মার্ট টেলিকম অ্যান্ড গ্যাজেট',
    category: 'Mobile, Telecom & Accessories' as const,
    businessType: 'Mobile & Telecom',
    businessModel: 'Retail & Service',
    template: 'Mobile & Telecom',
    role: 'owner' as const,
    isActive: true,
    storeSlug: 'smarttelecom-dhaka',
    plan: 'BUSINESS' as const,
  },
  {
    id: 'shop_102',
    name: 'স্মার্ট ফ্যাশন অ্যান্ড বুটিক',
    category: 'Fashion & Clothing' as const,
    businessType: 'Garments & Clothing',
    businessModel: 'Retail & Online Store',
    template: 'Fashion & Clothing',
    role: 'owner' as const,
    isActive: false,
    storeSlug: 'smartfashion-dhaka',
    plan: 'STARTER' as const,
  },
  {
    id: 'shop_103',
    name: 'স্মার্ট জেনারেল গ্রোসারি মার্ট',
    category: 'General & Trading' as const,
    businessType: 'Super Shop & Grocery',
    businessModel: 'Retail & Wholesale',
    template: 'General & Trading',
    role: 'owner' as const,
    isActive: false,
    storeSlug: 'smartgrocery-dhaka',
    plan: 'ENTERPRISE' as const,
  },
];

export const initialShop2: Shop = {
  id: 'shop_102',
  name: 'স্মার্ট ফ্যাশন অ্যান্ড বুটিক',
  ownerName: 'তানভীর আহমেদ',
  mobile: '01711002233',
  email: 'fashion@smartshopx.com',
  address: 'দোকান নং ১৫, গ্রাউন্ড ফ্লোর, পিংক সিটি, গুলশান-২, ঢাকা',
  category: 'Fashion & Clothing',
  customCategory: 'Men & Women Apparel',
  logo: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=150&auto=format&fit=crop&q=60',
  currency: 'BDT',
  subscriptionPlan: 'Standard',
  subscriptionStatus: 'Active',
  subscriptionStart: '2026-02-01',
  subscriptionExpiry: '2026-12-31',
  storeSlug: 'smartfashion-dhaka',
  storePublished: true,
  deliveryChargeInside: 60,
  deliveryChargeOutside: 120,
};

export const initialShop3: Shop = {
  id: 'shop_103',
  name: 'স্মার্ট জেনারেল গ্রোসারি মার্ট',
  ownerName: 'তানভীর আহমেদ',
  mobile: '01711002233',
  email: 'grocery@smartshopx.com',
  address: 'হাউজ নং ৮, রোড নং ৪, সেক্টর ৩, উত্তরা, ঢাকা',
  category: 'General & Trading',
  customCategory: 'Super Shop',
  currency: 'BDT',
  subscriptionPlan: 'Enterprise',
  subscriptionStatus: 'Active',
  subscriptionStart: '2026-01-15',
  subscriptionExpiry: '2026-12-31',
  storeSlug: 'smartgrocery-dhaka',
  storePublished: true,
  deliveryChargeInside: 50,
  deliveryChargeOutside: 100,
};

export const initialProductsShop2: Product[] = [
  {
    id: 'prod_f1',
    name: 'প্রিমিয়াম প্রিমিয়াম কটন পাঞ্জাবি (নেভি ব্লু)',
    sku: 'PJ-NV-42',
    barcode: '8901002001',
    category: 'পাঞ্জাবি',
    brand: 'Smart Fashion',
    purchasePrice: 1200,
    sellingPrice: 1950,
    discount: 150,
    stock: 24,
    minStock: 5,
    unit: 'পিস',
    description: '১০০% পিওর কটন ফেব্রিক ও আধুনিক এমব্রয়ডারি কাজ',
    image: 'https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-02-05',
  },
  {
    id: 'prod_f2',
    name: 'এক্সক্লুসিভ জর্জেট পার্টি শাড়ি',
    sku: 'SR-RED-01',
    barcode: '8901002002',
    category: 'শাড়ি',
    brand: 'Silk Touch',
    purchasePrice: 2800,
    sellingPrice: 4200,
    discount: 300,
    stock: 12,
    minStock: 3,
    unit: 'পিস',
    description: 'জরি এমব্রয়ডারি ও স্টোন ওয়ার্ক সহ জমকালো ডিজাইনার শাড়ি',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-02-10',
  },
  {
    id: 'prod_f3',
    name: 'ফরমাল স্ট্রেচ কটন শার্ট (হোয়াইট)',
    sku: 'SH-WH-L',
    barcode: '8901002003',
    category: 'শার্ট',
    brand: 'Smart Formal',
    purchasePrice: 750,
    sellingPrice: 1250,
    discount: 50,
    stock: 35,
    minStock: 8,
    unit: 'পিস',
    description: 'অফিস ও ক্যাজুয়াল পরিধানের প্রিমিয়াম সলিড কটন শার্ট',
    image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-02-12',
  },
];

export const initialProductsShop3: Product[] = [
  {
    id: 'prod_g1',
    name: 'প্রাণ চিনিগুড়া সুগন্ধি চাল (১ কেজি)',
    sku: 'RC-PRAN-1KG',
    barcode: '8941100221',
    category: 'চাল ও ডাল',
    brand: 'Pran',
    purchasePrice: 125,
    sellingPrice: 145,
    discount: 5,
    stock: 80,
    minStock: 20,
    unit: 'কেজি',
    description: 'উৎকৃষ্ট মানের সুগন্ধি পোলাও ও বিরিয়ানির চাল',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-01-20',
  },
  {
    id: 'prod_g2',
    name: 'রূপচাঁদা খাঁটি সয়াবিন তেল (৫ লিটার)',
    sku: 'OIL-RUP-5L',
    barcode: '8941100222',
    category: 'তেল ও ঘি',
    brand: 'Rupchanda',
    purchasePrice: 790,
    sellingPrice: 840,
    discount: 0,
    stock: 45,
    minStock: 10,
    unit: 'বোতল',
    description: 'ভিটামিন এ সমৃদ্ধ পুষ্টিকর রান্নার তেল',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&auto=format&fit=crop&q=60',
    isActive: true,
    onlineStoreVisible: true,
    createdAt: '2026-01-22',
  },
];

